//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application_Khinkalnaya
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD : DbContext
    {
        public BD()
            : base("name=BD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ОсобыеПоставки> ОсобыеПоставки { get; set; }
        public virtual DbSet<ОтветственныйЗаПоставки> ОтветственныйЗаПоставки { get; set; }
        public virtual DbSet<ПоставкиДляБара> ПоставкиДляБара { get; set; }
        public virtual DbSet<ПоставкиДляКухни> ПоставкиДляКухни { get; set; }
        public virtual DbSet<Поставщики> Поставщики { get; set; }
        public virtual DbSet<РасходнаяУтварь> РасходнаяУтварь { get; set; }
        public virtual DbSet<ТипПоставки> ТипПоставки { get; set; }
        public virtual DbSet<ТипПоставщика> ТипПоставщика { get; set; }
    }
}
